version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: messmate-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: messmate-db
    restart: always
    environment:
      POSTGRES_USER: messmate
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: messmate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
