"""renamed id to user id in user table

Revision ID: 050f86b20119
Revises: 5ea9369ac71a
Create Date: 2025-06-30 07:24:30.610114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '050f86b20119'
down_revision: Union[str, Sequence[str], None] = '5ea9369ac71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messes',
    sa.Column('mess_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('monthly_price', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('mess_id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_messes_mess_id'), 'messes', ['mess_id'], unique=False, schema='master')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_users_email'), 'users', ['email'], unique=True, schema='master')
    op.create_index(op.f('ix_master_users_user_id'), 'users', ['user_id'], unique=False, schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_users_user_id'), table_name='users', schema='master')
    op.drop_index(op.f('ix_master_users_email'), table_name='users', schema='master')
    op.drop_table('users', schema='master')
    op.drop_index(op.f('ix_master_messes_mess_id'), table_name='messes', schema='master')
    op.drop_table('messes', schema='master')
    # ### end Alembic commands ###
