"""initial table creation

Revision ID: 434d3e7626a4
Revises: c1464bfdbae9
Create Date: 2025-06-29 15:15:09.400554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434d3e7626a4'
down_revision: Union[str, Sequence[str], None] = 'c1464bfdbae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='master'
    )
    op.create_index(op.f('ix_master_users_email'), 'users', ['email'], unique=True, schema='master')
    op.create_index(op.f('ix_master_users_id'), 'users', ['id'], unique=False, schema='master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_users_id'), table_name='users', schema='master')
    op.drop_index(op.f('ix_master_users_email'), table_name='users', schema='master')
    op.drop_table('users', schema='master')
    # ### end Alembic commands ###
